#!/bin/bash
clientes=$(docker exec my-fwall sh -c 'exec mysql -uusfwall -pfwallpsw -e "select name from fwall.users"')

for u in $clientes
do
    if [[ "$u" == 'admin' ]]
        then
        continue
    fi
    if [[ "$u" == 'name' ]]
        then
        continue
    fi
	for j in b bs bp
	do
        echo "SELECT COUNT(block) AS '' FROM fwall.fwalls WHERE userId LIKE '"$u"' AND block LIKE '"$j"' AND time > DATE_SUB(NOW(),INTERVAL 24 HOUR) GROUP BY block;">totales.sql
        echo $u - $j
        total=$(docker exec -i my-fwall sh -c 'exec mysql -uusfwall -pfwallpsw' < totales.sql)
        if [ "$total" != '' ]
            then
            echo $total > $j.val
            else
            echo "0" > $j.val
        fi
    done
    echo 'INSERT INTO fwall.diarios(dia,userId,b,bs,bp) VALUES (SUBDATE(CURDATE(),1),"'$u'",'$(cat b.val)','$(cat bs.val)','$(cat bp.val)');' > tub.sql
    docker exec -i my-fwall sh -c 'exec mysql -uusfwall -pfwallpsw' < tub.sql
    docker exec -i my-fwall sh -c 'exec mysql -uusfwall -pfwallpsw' < fwall-clear.sql
done

